generic:
  deployment:
    image: tomsquest/docker-radicale:3.7.6.0
    ports:
    - containerPort: 5232
    pvcMounts:
      data:
        mountPath: /data
        hostPath: ~ # /mnt/storage/radicale/data
        backup:
          enabled: true
    configMapMounts:
      config:
        mountPath: /config
        configMapName: radicale-config-files
    secretMounts:
      htpasswd:
        mountPath: /etc/radicale-htpasswd
        secretName: radicale-htpasswd-secret
  service:
    ports:
    - name: http
      port: 5232
  ingress:
    https:
    - subdomain: dav
      port: 5232
      oauth: false
  configMaps:
    radicale-config-files:
      config: |
        [server]
        hosts = 0.0.0.0:5232
        max_connections = 20
        max_content_length = 100000000

        [auth]
        type = htpasswd
        htpasswd_filename = /etc/radicale-htpasswd/users
        htpasswd_encryption = bcrypt

        [rights]
        type = from_file
        file = /config/rights

        [storage]
        filesystem_folder = /data/collections

        [logging]
        level = info
  externalSecrets:
    radicale-htpasswd-secret:
    - users: "/radicale/HTPASSWD"
