{{- if .Values.watchdogHeartbeat.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watchdog-heartbeat-external-secret
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=true,SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ $.Values.global.externalSecrets.refreshInterval | default "1h" }}

  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.global.externalSecrets.clusterSecretStoreRef.name }}

  target:
    name: watchdog-heartbeat
    creationPolicy: Owner

  data:
    - secretKey: "watchdog_heartbeat_url"
      remoteRef:
        key: "{{ $.Values.global.akeyless.path }}/o11y/alertmanager/watchdog_heartbeat_url"
{{- end }}
