apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-controller
  namespace: {{ $.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: {{ .Values.certManager.version }}
    helm:
      valuesObject:
        crds:
          enabled: true
        featureGates: "ExperimentalGatewayAPISupport=true"
        dns01RecursiveNameservers: "1.1.1.1:53,8.8.8.8:53"
        dns01RecursiveNameserversOnly: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
