appName: pytr

generic:
  persistentVolumeClaims: {}
  externalSecrets: {}
  ingress:
    https:
    - subdomain: tr
      port: 8080
      service: pytr-login-service
      oauth: true

pytr:
  pytrVersion: "0.4.9"
  image: mcr.microsoft.com/playwright/python:v1.61.0-noble

  login:
    schedule: "0 0 1 1 *"
    suspend: true

  download:
    schedule: "0 2 1 * *"
    suspend: false
