generic:
  deployment:
    image: n8nio/n8n:2.15.1
    ports:
    - containerPort: 5678
    pvcMounts:
      data:
        mountPath: /home/node/.n8n
        hostPath: ~ # /mnt/somewhere/encrypted/apps/n8n/data
  service:
    ports:
    - name: http
      port: 5678
  ingress:
    https:
    - subdomain: n8n
      port: 5678
      middlewares:
      - oauth2-proxy
