{
 "title": "Magic Bag Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Magic Bag Availability",
   "type": "timeseries",
   "description": "Current availability of Magic Bags by location",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tgtg_item_count", "legendFormat": "{{display_name}}" }
   ]
  },
  {
   "title": "API Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tgtg_get_favorites_errors_total"
    }
   ]
  },
  {
   "title": "Notifications Sent Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "tgtg_send_notifications_total" }
   ]
  }
 ]
}