apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-controller
  namespace: {{ $.Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: {{ .Values.envoyGateway.chartVersion }}
    helm:
      valuesObject:
        config:
          envoyGateway:
            provider:
              type: Kubernetes
        deployment:
          envoyGateway:
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 512Mi
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.envoyGateway.namespace }}
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
