apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc-client-secret
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.global.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.global.externalSecrets.clusterSecretStoreRef.name }}
  target:
    name: oidc-client-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.global.akeyless.path }}{{ .Values.oidcClientSecretAkeylessPath }}
