{{- if .Values.samba.users }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: samba-secret-external-secret
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=true,SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.global.externalSecrets.refreshInterval | default "1h" }}

  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.global.externalSecrets.clusterSecretStoreRef.name }}

  target:
    name: samba-secret
    creationPolicy: Owner

  data:
    {{- range $user := .Values.samba.users }}
    {{- if not (hasPrefix "/" $user.akeylessPath) }}
    {{- fail (printf "User '%s' akeylessPath '%s' must start with '/'" $user.name $user.akeylessPath) }}
    {{- end }}
    - secretKey: "ACCOUNT_{{ $user.name }}"
      remoteRef:
        key: "{{ $.Values.global.akeyless.path }}{{ $user.akeylessPath }}"
    {{- end }}
{{- end }}
