apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: {{ .Values.global.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.global.externalSecrets.clusterSecretStoreRef.name }}
  target:
    name: oauth2-proxy
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: {{ .Values.global.akeyless.path }}{{ .Values.oauth2ProxyAkeylessPath }}/client_id
    - secretKey: client-secret
      remoteRef:
        key: {{ .Values.global.akeyless.path }}{{ .Values.oauth2ProxyAkeylessPath }}/client_secret
    - secretKey: cookie-secret
      remoteRef:
        key: {{ .Values.global.akeyless.path }}{{ .Values.oauth2ProxyAkeylessPath }}/cookie_secret
