{{- $security := $.Values.global.security | default dict }}
{{- $cloudflareCIDRs := $security.cloudflareCIDRs | default (list) }}
{{- $lanCIDRs := $security.lanCIDRs | default (list) }}
{{- $access := .Values.access | default "cloudflare-only" }}
{{- if ne $access "public" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oauth2-proxy-securitypolicy
  namespace: {{ .Values.global.gateway.namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=true,SkipDryRunOnMissingResource=true
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: oauth2-proxy
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          clientCIDRs:
            {{- if eq $access "cloudflare-only" }}
            {{- range $cloudflareCIDRs }}
            - {{ . }}
            {{- end }}
            {{- else if eq $access "cloudflare-and-lan" }}
            {{- range (concat $cloudflareCIDRs $lanCIDRs) }}
            - {{ . }}
            {{- end }}
            {{- end }}
{{- end }}
