# Local snapshot configuration for the hess.pm host.

jobs:

# Create and prune local snapshots.
- name: snapjob
  type: snap
  filesystems: {
    "tank1<": true,
    "hdd-z1<": true,
    "hdd-z2<": true,
    # Media is replaceable and intentionally not snapshotted.
    "hdd-z1/encrypted/media<": false
  }
  # Create snapshots with prefix `zrepl_` every 15 minutes.
  snapshotting:
    type: periodic
    interval: 15m
    prefix: zrepl_
  pruning:
    keep:
  # Fade-out scheme for snapshots starting with `zrepl_`:
  # - keep all created in the last hour
  # - then destroy snapshots such that we keep 24 each 1 hour apart
  # - then destroy snapshots such that we keep 14 each 1 day apart
  # - then destroy all older snapshots
    - type: grid
      grid: 1x1h(keep=all) | 24x1h | 35x1d | 6x30d
      regex: "^zrepl_.*"
  # Keep all snapshots that don't have the `zrepl_` prefix.
    - type: regex
      negate: true
      regex: "^zrepl_.*"
