{{- $oauth2Proxy := $.Values.global.oauth2Proxy | default dict }}
{{- $security := $.Values.global.security | default dict }}
{{- $cloudflareCIDRs := $security.cloudflareCIDRs | default (list) }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: argocd-securitypolicy-webhook
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: argocd-https-webhook
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          clientCIDRs:
            {{- range $cloudflareCIDRs }}
            - {{ . }}
            {{- end }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: argocd-securitypolicy-main
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: argocd-https-main
  extAuth:
    http:
      backendRefs:
        - name: {{ required "global.oauth2Proxy.service must be set" $oauth2Proxy.service }}
          namespace: {{ required "global.oauth2Proxy.namespace must be set" $oauth2Proxy.namespace }}
          port: {{ $oauth2Proxy.port | default 80 }}
      path: /oauth2/auth
      headersToBackend:
        - X-Auth-Request-User
        - X-Auth-Request-Email
  authorization:
    defaultAction: Deny
    rules:
      - action: Allow
        principal:
          clientCIDRs:
            {{- range $cloudflareCIDRs }}
            - {{ . }}
            {{- end }}
